export const city: string[] = [
  'Abidjan',
  'Abengourou',
  'Abobo',
  'Abomey',
  'Accra',
  'Adzope',
  'Yamoussoukro',
  'Bouake',
  'Daloa',
  'Diourbel',
  'Dolisie',
  'Gagnoa',
  'Grand-Bassam',
]

export const metiers: { label: string; value: string }[] = [
  { label: 'Maçon', value: 'Maçon' },
  { label: 'Plomberie', value: 'Plomberie' },
  { label: 'Electricité', value: 'Electricité' },
  { label: 'Maçonnerie', value: 'Maçonnerie' },
  { label: 'Menuisierie', value: 'Menuisierie' },
  { label: 'Mécanique', value: 'Mécanique' },
  { label: 'Métallurgie', value: 'Métallurgie' },
  { label: 'Pâtisserie', value: 'Pâtisserie' },
  { label: 'Téléphonie', value: 'Téléphonie' },
  { label: 'Travaux publics', value: 'Travaux publics' },
  { label: 'Transport', value: 'Transport' },
  { label: 'Vétérinaire', value: 'Vétérinaire' },
  { label: 'Viticulture', value: 'Viticulture' },
  { label: 'Zoologie', value: 'Zoologie' },
]

export const professions: string[] = [
  'Maçon',
  'Plomberie',
  'Electricité',
  'Maçonnerie',
  'Menuisierie',
  'Mécanique',
  'Métallurgie',
  'Pâtisserie',
  'Téléphonie',
  'Travaux publics',
  'Transport',
  'Vétérinaire',
  'Viticulture',
  'Zoologie',
  'Électricité',
  'Électronique',
  'Mécanique',
  'Métallurgie',
  'Pâtisserie',
  'Téléphonie',
  'Travaux publics',
  'Transport',
  'Vétérinaire',
  'Viticulture',
  'Zoologie',
  'Électricité',
]
